# Generated by Django 4.0 on 2022-01-04 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_client_company_serviceitem_company_and_more'),
        ('auth_email_verify', '0003_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='customers.company'),
            preserve_default=False,
        ),
    ]
