# Generated by Django 4.0 on 2022-03-05 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_client_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('idnumber', models.CharField(max_length=13)),
                ('dateofbirth', models.DateField()),
                ('mobilenumber', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=255)),
                ('startdate', models.DateField()),
                ('branch', models.CharField(max_length=255)),
                ('payrollname', models.CharField(max_length=255)),
                ('payfrequency', models.CharField(choices=[('W', 'Weekly'), ('B', 'Bi-Weekly'), ('M', 'Monthly')], max_length=3)),
                ('paytype', models.CharField(choices=[('S', 'Salary'), ('H', 'Hourly')], max_length=3)),
                ('salaryamount', models.IntegerField()),
                ('weekdayrate', models.FloatField()),
                ('saturdayrate', models.FloatField()),
                ('sundayrate', models.FloatField()),
                ('publicholidayrate', models.FloatField()),
                ('percentofpay', models.IntegerField()),
                ('maximumamount', models.IntegerField()),
                ('cutoffdate', models.DateField()),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.company')),
            ],
        ),
    ]
