# Generated by Django 4.0 on 2022-03-06 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_alter_employee_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='payrollname',
        ),
    ]
