# Generated by Django 4.0 on 2022-03-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_remove_employee_payrollname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='publicholidayrate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salaryamount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='saturdayrate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sundayrate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='weekdayrate',
            field=models.FloatField(null=True),
        ),
    ]
